# Generated by Django 5.2.18 on 2026-10-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("body", models.TextField()),
                ("score", models.IntegerField(db_index=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
